language: php

php:
- '5.6'

script: ant quick-build

addons:
  ssh_known_hosts:
    - $DEPLOY_HOST

after_success:
# Add Server to known_hosts manually because variables are not evaluated in addons phase.
- ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -p 2222 -H $DEPLOY_HOST 2>&1 | tee -a $HOME/.ssh/known_hosts
## Fetch VuFind and build package
#- curl http://heanet.dl.sourceforge.net/project/vufind/VuFind/2.3.1/vufind-$VUFIND_VERSION.tar.gz > vufind-$VUFIND_VERSION.tar.gz
#- tar xzf vufind-$VUFIND_VERSION.tar.gz
#- cp -R themes module ida languages solr vufind-$VUFIND_VERSION/
# SCP to Server
- chmod 0600 ssh_ida_travis_rsa
#- scp -C -r -i ssh_ida_travis_rsa -P 2222 -p vufind-$VUFIND_VERSION/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
#- scp -C -q -r -i ssh_ida_travis_rsa -P 2222 -p themes module ida languages solr $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
- rsync -az -e "ssh -p 2222 -i ssh_ida_travis_rsa" themes module ida languages solr $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

before_install:
- openssl aes-256-cbc -K $encrypted_6dde9588b8f6_key -iv $encrypted_6dde9588b8f6_iv
  -in ssh_ida_travis_rsa.enc -out ssh_ida_travis_rsa -d

env:
  global:
    - "VUFIND_VERSION=2.3.1"
    - secure: cwcm/6sqXrjgEWxVi90NgIYkpEZ1phjSCDPvEZzlZay1/ykmcVylmGGA3ywEc1vICD+KHHCS8LuFEHMlAHGDmrA+373RCHMg5219uxTXio2ZWAIAfzG3MYgCNKo/lXor2OxTeHB/3VJON73El7q8Pm3HLbcsGHjxp0thOvJcYf7EbRuP9VKmkjw9LLo/cCFENMjhc6eVrDq4ZV2CXOh2W1WlBs/6fFfBxi+HczUnRrsLM5zPP7HFizS9m429c64/W+yLtfZ43A3Un3RwlyQ9caI83CeCZY5+DuCe60eevWzY031W3uxQrbh9fRGXZLQtgwo7vy23x9e9ff8LqErEnyNZ/4ZtZ+/cIBOSdl7d8HJBAD7e2f7aAXSScpIncAtz7mrUBuAckG4ZykjFYsdznk/+5gQlVVyJF8Nj9C/eA89+EWb3BfXJiwq6TR72E8MvtU5bvjgCzYUxLFplvhzM8E4iXOtjYAxidJBhqqzhWBd+4xRO/FKNVkKbmhv9qUaY0Ve0GTxdLYU7MU0624rmZAR6aqD7BhmWvCI3M/mFnm+HDpE5VDs38YAcFwnLRsNE0VuJ3gsmVg1o2TVGRxSOUco6TlhQPoUHqFzqj/E3TB85nvr5mNWc0rlcKU49fo0JAaHPNYr21AId1J1L88lK8trRWLs1NQVJMxopr7x3dYE=
    - secure: cm3IiLYFJFM1jAOkQRsjXn74VGNjjWT4gW4HtAfIrfJ8Y5NulJW5rmcieLTXHoZ91kLxlunI+kIk4SmYb0jtl9hBiu4bTuKoE7z6tCxH73sqe0c5lgZzXgO2Y3L/oIGz6o3Kxpjmd3+pNXYSH96B3Hos/0ehMcbBKzGktuMu+6Sa8aOAonL2FczbFJ7CgOZ2wJHEnKNiX4vsfaEqznfT3CARP4/dKEm6MZws57LYGBBPWICuLQM6o36lSTM7aGu0qcIYBsGA14toWvwiBGtnO6c9EWjkG8/HXirT3OCtK2GZc5+H8PJ1DvxxMkBCazIvsKWP89z4pXOCV7+/sS5Q2DODMftYVP2Uw+DcreriILl5i5AplR7TufNcW+ADEpdhuykOc3373K6Ga95r0MBoDQlmCYVBx/JdO8mXuzrxI9Yl5PPPp2FPxYiKErU2cEHjXrw7/rPU+iRZ4v48BzWCS0x31CtqtejGLn9Q5wK9T+rvn8D6lNCo7o7b0KIxDiBuuw2XOqsk9/osLl81lxVQ0wXqGZakMkscHtXANjol9jnw0UYWhTP60qqDWqrhBytUxz/w6JkCpXNJaoftGMC3MaJn67i+4ZSka9FoF67hV68IoEokqJBujOgizHBGLHtYnA79xuJXoLUG8zN6NV0/mamQzyF9arNJYzLXc6vt8O8=
    - secure: Rpf7ixOr/fSBp9JIQFR0DQyOFJnXsnfshC84lVSSFPsi9lN9K85uVrTcBTevaVBjairANeglCP7nCb1rxn31efsxVR2fQRaYFSNUOsoDUk6yIVaRKDmmiPZmrjtDYxgqR1pvgmE02YCDrRuA5/ucaFFVaiUpK1TCwErkDsuYPvlyC8w4QenxG5GLTGFlJh+6tIx6CWuGth9t0r48tWSvruGtm+ljO/J01/5mKr5BazKvWeIiPpBekwKckVh9BQXPIwE5KyD/nOcljY0AOYkOEFP07Rh29PWLO8nwq6z5V096A5+ny3sMxBhWRyFPYYWEiFiyI6P5OvMcGpAZvItyjsAkLOJdTqqIWYWCYhbtx4OBHIBa5sUhv/yt9InGKFJnIhT4OlY9YAMzGWxAzzmGq93Fe9B0F563z6CZ35KBvvcR5DMa+pxz+HZ4yuZOx3MOAJlw7tczF5BK0C14xkBJ8kV4mozlgCw5ZAno0Me1XouYfgi5vAZ0pObQWCHKBPwaLahMKjAiAAUuNJ8gM0F/NO2fHHQFo9aRDRYIIo03mISxUXK25pfL7S3IXJLjOlDtwRDTgmozpv0tA2jypVV3gnLWv13ywcQGZehYiM4jqYEryaYQ7G/Ur/RFPZdnlnSh7kz8D4V9Wcw5MqCmtmS63Dc7KVYSpZDQ0Vykr7Nnp1U=
    - secure: Q5QJZsJKkfmc0GI1uqiJlEYkbSjpZtOSLGxs9Z2hBpqgQgdQi/FtSEdF1d61C2jM+uMu3EExzQUFJbE/36d9n506jQypOoEEBmjzeBhZUnHbytWND0eSWRYQiOmiHyRozPveIkUvkx7/P0/jcbxw9E+IoYnAwQ+t1TXdUfbD1YMjEk/vHVmY7xVyJ4sLJ42E0m2l9jCrzQBWdmpWVGHqe2Yh4lenUhWQJi/ViBYelLckqQKwjNM45+na/myn+t+ir8mpj4A/r84Ac4DsUaFChFX2XJFE+mBvdQETYszfwLM9NUULEl+2B2PSMDLZLa46NT8q1V/6n+KQ3O2wMUc0vNRskZBFl4TwLRysatW36aa9jVVUoLDPKuZ/dUZCkCiEWamnYnkKwnm/vXw43ZocSwWdMMd/+rbLQQmJrUwbZZC2FGPHrHIDhaDEk9fxuS6A47lHygxgL2vlK9v4GePTBv8XedARhtGwDQoqWkBtPZqXlfNjQJpMK5nOf8tlTDw/NYWfvAe3+uOjgvDEewVjEECrrBaJ9g9TIL4Yls4XjR+ryfUMWsVS7cHOnkpool7IlehYB8J8K+A8mCC44J1BxtzkNawPRI6wh5Yq7NkQADnGKzO4b11i5YPZsRkT5jDoFPGWx50A8o2vdj3rE4Tony9q+QkrxKkDiJ65MMwW+d0=
