language: php

php:
- '5.6'

script: ant

addons:
  ssh_known_hosts:
    - $DEPLOY_HOST

after_success:
- mkdir build- chmod 600 deploy-key
- mv ssh_ida_travis_rsa ~/.ssh/id_rsa
# Add Server to known_hosts manually because variables are not evaluated in addons phase.
- ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
#- sshpass -e scp -r ??package.tgz -p 2222 $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
- curl http://heanet.dl.sourceforge.net/project/vufind/VuFind/2.3.1/vufind-$VUFIND_VERSION.tar.gz > vufind-$VUFIND_VERSION.tar.gz
- tar xzf vufind-$VUFIND_VERSION.tar.gz
- cp -R themes module ida languages solr vufind-$VUFIND_VERSION/
- scp -r  vufind-$VUFIND_VERSION/* -P 2222 -p $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

before_install:
- openssl aes-256-cbc -K $encrypted_6dde9588b8f6_key -iv $encrypted_6dde9588b8f6_iv
  -in ssh_ida_travis_rsa.enc -out ssh_ida_travis_rsa -d

env:
  global:
    - "VUFIND_VERSION=2.3.1"
    - secure: cwcm/6sqXrjgEWxVi90NgIYkpEZ1phjSCDPvEZzlZay1/ykmcVylmGGA3ywEc1vICD+KHHCS8LuFEHMlAHGDmrA+373RCHMg5219uxTXio2ZWAIAfzG3MYgCNKo/lXor2OxTeHB/3VJON73El7q8Pm3HLbcsGHjxp0thOvJcYf7EbRuP9VKmkjw9LLo/cCFENMjhc6eVrDq4ZV2CXOh2W1WlBs/6fFfBxi+HczUnRrsLM5zPP7HFizS9m429c64/W+yLtfZ43A3Un3RwlyQ9caI83CeCZY5+DuCe60eevWzY031W3uxQrbh9fRGXZLQtgwo7vy23x9e9ff8LqErEnyNZ/4ZtZ+/cIBOSdl7d8HJBAD7e2f7aAXSScpIncAtz7mrUBuAckG4ZykjFYsdznk/+5gQlVVyJF8Nj9C/eA89+EWb3BfXJiwq6TR72E8MvtU5bvjgCzYUxLFplvhzM8E4iXOtjYAxidJBhqqzhWBd+4xRO/FKNVkKbmhv9qUaY0Ve0GTxdLYU7MU0624rmZAR6aqD7BhmWvCI3M/mFnm+HDpE5VDs38YAcFwnLRsNE0VuJ3gsmVg1o2TVGRxSOUco6TlhQPoUHqFzqj/E3TB85nvr5mNWc0rlcKU49fo0JAaHPNYr21AId1J1L88lK8trRWLs1NQVJMxopr7x3dYE=
  # DEPLOY_USER:
    - secure: IS7+MhjCH+UKftDoUQXOc2ooA9SOG61ODy+GqBQT8PGDf+cxind1JLGRyIYwVlU779SNYE84YZp3W86zSi9n0NfIBFhqAE1nJrAFLO4B+AeHZ2PYbW9Ll/ODpJan4sMm73ICuaRIn6srQO4d3p6uPuOk+VLMqsvMAI1ZyhOvPHe22PLNzkBQfXcrcvAoqJwFPGAyoXwKLOQuFuQXTpngNgmwSbfB/ufM5ZWkZhPjY9b69l6WWJ7HOhvgfJDh9bKk/a3deeexCZitFxFrEHLnnATf87xgaVx8xbxY4vkEs9VCzBpsMwWo9PyxnXZP+n6FazbXr3ENfpTCaknePKue9nbxQFXPVxzmhiJKRwa/tL8lssTkMmdRX2wuuWH1g0kzxDjm9l4DWsRpH7Di8OTG8qwwIXBZbjMzZUfaFoX5riSRN0fQUx70ecZfzEfJlxIpgBXziWUR1+GFfv4qA6owSqTpnIDaxAbiu4TrMeJ7lE1kEHnvEpNYd3MEfVeoH8zPZuicQai6B4B2jvtnRcgdAH1hT5zKN0GTg6LXfBeOTD6hqV88xwCNsAkt61Wry5Qc+xz0iy8fc2H0uxZ6s28/J092QoM/f8lSxigs1cJU2jVCgnEzybs6FAeAc0GACHk84eIuZ/0fFevRWOp9VmdCrH6wX8kzpSYAj6AgnDoHDpM=
  # DEPLOY_HOST:
    - secure: ZdVdH9TFQk6wdQg8nZKGl7t887UTIKVqbcf08yVojSlSotobnegY0M8Ph98q63zICJC57iU5AqFwydi0qcexksrXhAwaX3GOyIKi/GBPJuJf/RWEvmcRoKNjvAEuV25VNxXvGjgMd0l3eVQQGvyUfbvX6YavKsD79mOqzBPLKeqJDFtxU4HUf025wxqjRiS7wcbf7KxuyV/6KkURvjPciysUGFNMFGl+AON3KpdI6BgQ2tEuemuc6zBqmmxZmMfBXrzld7tQV6S6MpcBHTYNNOPNCHzlJJvXPe/8gd6vF+XREI68ujl/fx2M+MOd7iVcOUxkXTZX5C5MtPbX83O4BOXRixXj/QjAEcxqnyyKfS4YXMrc2QA30pto7Q/W43jD81G9XM9fwdAkA4mQUtlN5Uxatv6U+2IAXD0XK7B9VcIpCsEKyaS18rAvztCsrBeec+VJySxamJUwu3k64HUZMUzgDVpfWqmElw6clzfLGmOzo65ofiITJLQ60UEt2p/Lz2tEcAkYHrfnV0nH6McmfBSVSL66Ik+S6EAiQAXcHl1Cj+hzzD6Y0kQDQrkiwWMiLJOgh70SIbZfiqQSqR3//Csd75INFjoKppyXldMuFpByymOGSdgHhCe2BBzdnuJG9xnVrhbB/RpRHb9QBp0yPiN2Kbv1hTqlAx/isjXKrUk=
  # DEPLOY_PATH:
    - secure: dwpG+rP6gXxihj+YcR1Ht3bV5GMdyKvn7wyJXxqK5OyKrxG2T1SYcaDy11yeluzmcvfgnVjq5tjKp9FEACn/r78TqSvgBw5VbjUs5/FET+Q1PXeZC1VcLUCA3nWAuokG+q2eSnJLADO9MAZ4RGm9VtsXyDR+2ie7QKr9wqy8ng7BAsPctjRmPkBYUY73ngM5q+rfa8T8PWDgyeSv0otm76q0n35D3wtXgnIAnVvpU12EkzfdcLiNAMye7kV8fg3qcmwtUa5C4DcPIfQvt7j4KV8xjTDngc6PwBiRKxnrMBeF0nN42Oy3Irr78rJco5Qb217DMFBoFFdLMao0hIHDIatf1c9JbxVa0Ittbepz49nCp95IG659yMFQLr2Px1A2SPf2SfYxRhr3LfZR9E1aQSTkJEKJmXdaPVSK/nn4SvjeVgeFk/LdnhDitguOdQyoLN/iCeEsRVR5eBpx4+Jz7ZIoNPp4yUzYWOcZJG1IwFQ3eRJkYczoKpCxwCKHlg8CE8E4PjFpdceVD+hlz/aNTQjmk0Nuxbvhh4jibDsRAxl+YQSSdPShEUR0B+TF6h1qnrOeSbv2b9LkMbki0pReMdRrvAHAgxTCWYk8EHCe9IJe/Id9qMitD7gcyHpAe/75dIAtaO/Y+UDgvZOrN07IKYHgzlNzHYCauBKq/nMuyZQ=
